tests: Update to use GTK 4
Otherwise they will fail with:

    Error: Requiring Gdk, version 3.0: Typelib file for namespace 'Gdk', version '3.0' not found